</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='un-RAR utility'
VERSION=2.71 #ancient but the latest pure C variant I have found
#DEPS=

WEBSOURCE=http://ibiblio.org/pub/linux/utils/compress/unrar-2.71.tar.gz
BUILDPATH=work/unrar-2.71
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
