</$objtype/mkfile 
LIB=/$objtype/lib/ape/libxml2.a

OFILES= SAX.$O entities.$O encoding.$O error.$O \
	parserInternals.$O parser.$O tree.$O hash.$O list.$O xmlIO.$O \
	xmlmemory.$O uri.$O valid.$O xlink.$O HTMLparser.$O \
	HTMLtree.$O debugXML.$O xpath.$O xpointer.$O xinclude.$O \
	nanohttp.$O nanoftp.$O DOCBparser.$O catalog.$O globals.$O \
	threads.$O c14n.$O xmlstring.$O buf.$O xmlregexp.$O \
	xmlschemas.$O xmlschemastypes.$O xmlunicode.$O \
	triostr.$O trio.$O xmlreader.$O relaxng.$O dict.$O SAX2.$O \
	xmlwriter.$O legacy.$O chvalid.$O pattern.$O xmlsave.$O \
	xmlmodule.$O schematron.$O xzlib.$O

HFILES=libxml.h include/libxml/xmlexports.h include/libxml/xmlversion.h config.h 

</sys/src/cmd/mksyslib

CC=pcc
LD=pcc
CFLAGS=-c -I. -I./include -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_BSD_EXTENSION -DHAVE_SYS_SOCKET_H -DHAVE_NETDB_H -DHAVE_GETADDRINFO -DHAVE_SYS_SELECT_H -DHAVE_ERRNO_H -DHAVE_CONFIG_H -D_C99_SNPRINTF_EXTENSION -DECONNRESET=0

SAX.$O:
entities.$O:
 
nuke:V:
	mk clean
	rm -f $LIB
	rm -f /sys/man/3/libxml
	rm -f /sys/man/1/xml2-config
	rm -rf /sys/include/ape/libxml
	rm -f /rc/bin/ape/xml2-config
	mk -f mkfile.bin nuke
	

install:V:
	cp libxml.3 /sys/man/3/libxml
	cp xml2-config.1 /sys/man/1/xml2-config
	cp xml2-config /rc/bin/ape/
	mkdir -p /sys/include/ape/libxml
	dircp include/libxml /sys/include/ape/libxml
	mk -f mkfile.bin install

