</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='Open codec designed for internet transmission of interactive speech and audio'
VERSION=1.2.1

WEBSOURCE=https://archive.mozilla.org/pub/opus/opus-$VERSION.tar.gz
BUILDPATH=work/opus-$VERSION
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
