</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='GNU awk'
VERSION=4.1.4
DEPS=ape-libs/gnulib

WEBSOURCE=https://gnu.cu.be/gawk/gawk-$VERSION.tar.gz
WORKFILE=gawk-$VERSION.tar.gz
EXTRACTCOMMAND=tar xzf
PATCHES=files
BUILDPATH=work/gawk-$VERSION
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
