</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='GNU awk'
VERSION=4.1.3
DEPS=ape-libs/gnulib

WEBSOURCE=https://gnu.cu.be/gawk/gawk-4.1.3.tar.gz
WORKFILE=gawk-4.1.3.tar.gz
EXTRACTCOMMAND=tar xzvf
PATCHES=files
BUILDPATH=work/gawk-4.1.3
BUILDCOMMAND=mk 
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean

</sys/ports/Mk/mkfile
