</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='Quasar m4 : minimal GNU m4-compatible implementation'
VERSION=1
DEPS=ape-libs/gnulib ape-libs/headers

WEBSOURCE=http://haddonthethird.net/m4/m4-2.tar.bz2
BUILDPATH=work/m4-2
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
