</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='xz utilities and liblzma for APE'
VERSION=5.2.1
#DEPS=

WEBSOURCE=http://tukaani.org/xz/xz-5.2.1.tar.bz2
WORKFILE=xz-5.2.1.tar.bz2
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/xz-5.2.1
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
