</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='expat XML parser library for APE'
VERSION=2.1.0

WEBSOURCE=http://kent.dl.sourceforge.net/project/expat/expat/2.1.0/expat-2.1.0.tar.gz
BUILDPATH=work/expat-2.1.0
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
