</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='Go Discord client'
VERSION=2.1
DEPS=dev-lang/go

WEBSOURCE=https://bitbucket.org/henesy/disco/get/2.1.tar.gz
BUILDPATH=work/disco
BUILDCOMMAND=getdeps.rc && mk
CLEANCOMMAND=rm work/disco/disco
INSTALLCOMMAND=cp work/disco/disco /$objtype/bin/disco
UNINSTALLCOMMAND=rm /$objtype/bin/disco

</sys/ports/Mk/mkfile
