</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='Go Discord client'
VERSION=2.1
DEPS=dev-lang/go

WEBSOURCE=https://bitbucket.org/henesy/disco/get/2.1.tar.gz
BUILDPATH=work/henesy-disco-ad91578eda4b
BUILDCOMMAND='GOPATH=$home/go; mkdir -p $GOPATH/src/bitbucket.org/henesy/disco && bind ../henesy-disco-ad91578eda4b $GOPATH/src/bitbucket.org/henesy/disco && ./getdeps.rc && go build'
CLEANCOMMAND=rm henesy-disco-ad91578eda4b
INSTALLCOMMAND=cp henesy-disco-ad91578eda4b /$objtype/bin/disco
UNINSTALLCOMMAND=rm /$objtype/bin/disco

</sys/ports/Mk/mkfile
