</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='C-language version of lzip'
VERSION=1.10
DEPS=ape-libs/headers

WEBSOURCE=http://download.savannah.gnu.org/releases/lzip/clzip/clzip-$VERSION.tar.gz
WORKFILE=clzip-$VERSION.tar.gz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/clzip-$VERSION
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
