</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='game from fgb/breakout'
VERSION=1

WEBSOURCE=http://9.postnix.pw/code/ports/breakout.tgz
BUILDPATH=work/breakout
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
