</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='PDCurses port to APE'
VERSION=3.4

WEBSOURCE=http://kent.dl.sourceforge.net/project/pdcurses/pdcurses/3.4/PDCurses-3.4.tar.gz
BUILDPATH=work/PDCurses-3.4
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
