
info:VQ:
	echo 'Name: '^$PORTNAME
	echo 'Description: '^$DESCRIPTION
	echo 'Complain to: '^$OWNER

fetch:VQ:
	if(! test -e work/)
		mkdir work/
	if(test -e /env/WEBSOURCE){
		webfs
		. /sys/ports/Config/ports.conf
		hget $WEBSOURCE > work/$WORKFILE
		$EXTRACTCOMMAND=($EXTRACTCOMMAND 'work/'^$WORKFILE)
		eval $EXTRACTCOMMAND
	}
	if(test -e /env/CONTRIBSOURCE){
		9fs sources
		dircp $CONTRIBSOURCE work/
	}
	if(! ~ $#HGSOURCE 0){
		webfs
		hg clone $HGSOURCE work/
	}

build:VQ:
	if(test -e /env/PATCHES){
		dircp $PATCHES $BUILDPATH
	}
	. /sys/ports/Config/ports.conf
	cd $BUILDPATH
	for(i in (arm 386 amd64)){
		{
			rfork ne
			objtype=$i
			eval $BUILDCOMMAND
		}
	}

install:VQ:
	. /sys/ports/Config/ports.conf
	cd $BUILDPATH
	for(i in (arm 386 amd64)){
		{
			rfork ne
			objtype=$i
			eval $BUILDCOMMAND
		}
	}

clean:VQ:
	. /sys/ports/Config/ports.conf
	cd $BUILDPATH
	eval $CLEANCOMMAND

nuke:VQ:
	. /sys/ports/Config/ports.conf
	rm -rf work/
