</sys/ports/Config/ports.mk.conf
# </sys/ports/Mk/newvars.mk  # For Aram

# for compatibility
BUILDFOR=$objtype
PORTID=`{echo $PORTNAME | md5sum}
PORTCAT=`{basename -d `{pwd} | sed 's,.*/,,'}
PORTNAME=$PORTCAT/`{pbd}
files=`{pwd}/files

# for ease of use
BUILDPATH=`{ if(~ $#BUILDPATH 0){ echo 'work/' }; if not { echo $BUILDPATH }}
archmask=`{ if(! ~ $#ARCHMASK 0) { echo $ARCHMASK } }

all:VQE:	install

info:VQE:
	echo 'Name: ' $PORTNAME
	if(! ~ $VERSION 0){
		echo 'Port Version: ' $VERSION
	}
	echo 'Description: ' $DESCRIPTION
	echo 'Complain to: ' $OWNER

check:VQE:
	. $PORTS/Mk/lib.rc
	qa

fetch:VQ:
	. $PORTS/Mk/lib.rc
	# setup our own webfs/ua, mainly for sourceforge
	rfork n
	unmount /mnt/web || status=''
	webfs
	echo useragent curl/7.28.1 > /mnt/web/ctl
	
	for(p in `{distfiles}) @{
		if(! test -f $DISTFILES/$PORTNAME/$p)
			exit 'nothave'
		status=''
	} && exit
	
	echo 'fetching distfiles for '^$PORTNAME
	# avoid a bug in mk, which executes prereqs when mtimes are equal.
	test -e $target && exit
	test -e patch && rm patch
	
	# ensure distfiles exists
	if(! test -d $DISTFILES){
		mkdir $DISTFILES
		chmod +t $DISTFILES
	}
	
	if(! test -d $DISTFILES/$PORTNAME)
		mkdir -p $DISTFILES/$PORTNAME
	
	# dowload multiple http files, possibly with new names
	if(! ~ $#WEBSOURCE 0){
		for(s in $WEBSOURCE){
			eval `{uriextract $s}
			if(! test -r $DISTFILES/$PORTNAME/$local)
				V hget -o $DISTFILES/$PORTNAME/$local $remote
			rm -f /env/^(local remote)
		}
	}
	
	if(! ~ $#9PSERVER 0){
		rfork n
		V $PORTS/Mk/ports9fs $9PSERVER
	}
	
	if(! ~ $#9PFILE 0){
		for(s in $9PFILE){
			eval `{uriextract $s}
			if(! test -r $DISTFILES/$PORTNAME/$local)
				V fcp $remote $DISTFILES/$PORTNAME/$local
			if not status=''
			rm -f /env/^(local remote)
		}
	}
	
	if(! ~ $#9PDIR 0){
		for(s in $9PDIR){
			eval `{uriextract $s}
			if(! test -d $DISTFILES/$PORTNAME/$local){
				V mkdir -p $DISTFILES/$PORTNAME/$local
				V $PORTS/Mk/portsdircp $remote $DISTFILES/$PORTNAME/$local
			}
			if not status=''
			rm -f /env/^(local remote)
		}
	}
	
	if(! ~ $#HGSOURCE 0){
		eval `{uriextract $HGSOURCE}
		if(! test -d $DISTFILES/$PORTNAME/$local){
			v='--quiet'
			if(~ $V 2) v=()
			if(~ $#HGREV 0) HGREV=tip
			V hg $v clone -r $HGREV $remote $DISTFILES/$PORTNAME/$local
		}
		rm -f /env/^(local remote v)
	}
	status=''

distfiles:Q:
	. $PORTS/Mk/lib.rc
	distfiles

distclean:Q:	nuke
	echo removing $DISTFILES/$PORTNAME
	rm -rf $DISTFILES/$PORTNAME

manifest:QD:	fetch
	. /sys/ports/Mk/lib.rc
	test -e manifest && exit 'manifest already exists'
	echo creating manifest
	distfiles | @{ cd $DISTFILES/$PORTNAME; xargs sha1sum -2 256 } > manifest

verify:DQ:	fetch
	. /sys/ports/Mk/lib.rc
	test -e manifest || exit 'missing manifest'
	test -e $target && exit
	
	echo verifying manifest
	distfiles | @{ cd $DISTFILES/$PORTNAME; xargs sha1sum -2 256 } > verify
	
	if(cmp -s manifest verify)
		exit
	
	s='MANIFEST VERFICATION FAILED'
	echo $s
	echo file sums changed:
	ape/diff -u manifest verify
	exit $s

_extract:VQ:


extract:DQ:	verify
	. /sys/ports/Mk/lib.rc
	test -e $target && exit
	test -e patch && rm patch
	mkdir -p work
	echo extracting distfiles
	for(l in `{distfiles}) @{
		cd work
		extract $DISTFILES/$PORTNAME/$l
	}
	if(! ~ $#HGSOURCE 0) @{
		eval `{uriextract $"HGSOURCE}
		cd work
		extract $DISTFILES/$PORTNAME/$local
		rm -f /env/^(local remote)
	}
	touch $target

patch:QE:	extract
	. /sys/ports/Mk/lib.rc
	# avoid a bug in mk, which executes prereqs when mtimes are equal.
	test -e $target && exit
	echo patching $PORTNAME
	for(p in `{ls $files/*.patch >[2]/dev/null}){
		@{ cd $BUILDPATH && apply $p } || exit 'applying '^$p^' failed'
	}
	if(test -d $files){
		$PORTS/Mk/portsdircp $files $BUILDPATH
	}
	touch $target

unpatch:VQE:	$BUILDPATH
	. /sys/ports/Mk/lib.rc
	test -e patch || exit 'not patched'
	for(p in `{ls $files/*.patch >[2]/dev/null}){
		@{ cd $BUILDPATH && unapply $p } || exit 'unapplying '^$p^' failed'
	}
	rm -f patch

build:QE:	patch
	. /sys/ports/Mk/lib.rc
	if(! ~ $#archmask 0){
		if(! ~ $#IGNOREMASKS 0){
			for(i in $archmask){
				if(~ $i $objtype){
					exit 'objtype '^$"objtype^' is not supported'
				}
			}
		}
		if not {
			echo 'warning: ignoring architecture build masks'
		}
	}
	if(! ~ $#DEPS 0){
		echo 'installing dependencies...'
		for(i in $DEPS){
			if(! checkport $i){
				@{
					# hacky. plz fix.
					rfork nE
					PORTS=$PORTS
					home=$home
					objtype=$objtype
					cputype=$cputype
					cd $PORTS/$i
					echo 'installing dependent port '^$i^'...'
					mk all
				}
			}
		}
	}
	@{
		rfork ne
		cd $BUILDPATH
		if(~ $#BUILDCOMMAND 0)
			BUILDCOMMAND=mk
		eval $BUILDCOMMAND || exit $status
		if(! ~ $#POSTBUILD 0){
			echo 'Running post-build hooks...'
			eval $POSTBUILD || exit $status
		}
	}
	touch build

test:VQE:	build
	. /sys/ports/Mk/lib.rc
	if(! ~ $#archmask 0){
		for(i in $archmask){
			if(~ $i $objtype){
				exit 'objtype '^$"objtype^' is not supported'
			}
		}
	}
	@{
		rfork ne
		cd $BUILDPATH
		if(! ~ $#TESTCOMMAND 0){
			eval $TESTCOMMAND
			if(! ~ $status ''){
				echo 'Tests failed. Please notify '^$OWNER
				status='tests failed'
			}
			if not {
				echo 'Tests completed successfully!'
				status=''
			}
		}
		if not {
			echo 'tests aren''t supported on this port'
			status='no tests'
		}
	}
	exit ''

install:QE:	build
	. /sys/ports/Mk/lib.rc
	if(! ~ $#BUILDONLY 0){
		for(i in $BUILDONLY){
			if(~ $i $objtype){
				exit 'objtype '^$"objtype^' is not supported.'
			}
		}
	}
	if(! checkport $PORTNAME){
		if(~ $#INSTALLCOMMAND 0)
			INSTALLCOMMAND=mk install
		@{ rfork ne; cd $BUILDPATH && eval $INSTALLCOMMAND } || exit $status
		if(! ~ $#VERSION 0){
			register $PORTNAME $VERSION
		}
		if not {
			register $PORTNAME '0'
		}
		if(! ~ $#MESSAGE 0){
			for(i in $MESSAGE){
				echo $i
			}
		}
		if(! ~ $#MSGFILE 0){
			cat $MSGFILE
		}
		touch install
	}
	if not {
		echo $PORTNAME is already installed
		status=''
	}

reinstall:VQE:	build
	. /sys/ports/Mk/lib.rc
	cd $BUILDPATH
	@{
		rfork ne
		if(~ $#INSTALLCOMMAND 0)
			INSTALLCOMMAND=mk install
		eval $INSTALLCOMMAND
	}
	if(! ~ $*MESSAGE 0){
		for(i in $MESSAGE){
			echo $i
		}
	}

testinstall:VQE:
	. /sys/ports/Mk/lib.rc
	cd $BUILDPATH
	@{
		rfork ne
		if(~ $#INSTALLCOMMAND 0)
			INSTALLCOMMAND=mk install
		eval $INSTALLCOMMAND
	}
	if(! ~ $*MESSAGE 0){
		for(i in $MESSAGE){
			echo $i
		}
	}
	status=''

clean:VQE:	$BUILDPATH
	@{
		rfork ne
		cd $BUILDPATH || exit 'not fetched'
		if(! ~ $#NOCLEAN 0) {
			exit
		}
		if(! ~ $#CLEANCOMMAND 0){
			eval $CLEANCOMMAND || exit $status
		}
	}
	rm -f build
	status=''

nuke:VQ:
	rm -rf work/
	rm -f fetch verify extract patch build install

uninstall:VQE:
	. /sys/ports/Mk/lib.rc
	if(! checkport $PORTNAME){
		echo $PORTNAME is not installed
		exit notinstalled
	}
	echo removing $PORTNAME...
	if(~ $#UNINSTALL 0 && ~ $#UNINSTALLCOMMAND 0){
		if(test -e $PORTS^$PORTNAME^'/uninstall'){
			UINSTALLCOMMAND=$PORTS^$PORTNAME^/'uninstall'
		}
		if not {
			echo 'unable to uninstall port'
			echo 'please send a bug report to '^$OWNER^' about this'
			echo 'If '^$OWNER^' does not respond or fix the port please'
			echo 'email mveety@gmail.com, and he will remove the port.'
			exit nouninstall
		}
	}
	if(~ $#UNINSTALLCOMMAND 0){
		for(i in $UNINSTALL){
			echo 'removing '''^$i^'''...'
			rm -f $i
		}
	}
	if not {
		@{
			rfork ne
			cd $BUILDPATH
			eval $UNINSTALLCOMMAND
		} || exit $status
	}
	deregister $PORTNAME
	rm -f install
