</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='decontrib'
VERSION=0

9PSERVER=9pio
9PFILE=/n/9pio/contrib/john/decontrib
INSTALLCOMMAND=chmod +x decontrib && cp decontrib /rc/bin/decontrib
UNINSTALL=/rc/bin/decontrib

</sys/ports/Mk/mkfile
