</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='XScreenSaver ports'

9PSERVER=9front.org
9PFILE=/n/9front.org/extra/xscr.tgz
WORKFILE=xscr.tgz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/xscr
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=rm -rf /$objtype/bin/xscr

</sys/ports/Mk/mkfile
