</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='XScreenSaver ports'

WEBSOURCE=http://9front.org/extra/xscr.tgz
WORKFILE=xscr.tgz
EXTRACTCOMMAND=/bin/tar xzvf
BUILDPATH=work/xscr
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCMD=rm -rf /$objtype/bin/xscr

</sys/ports/Mk/mkfile
