</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='Optionally use mksh as default /bin/sh in APE'
DEPS=app-shells/mksh
VERSION=0

BUILDPATH=work/
BUILDCOMMAND=fortune
INSTALLCOMMAND=cp /$objtype/bin/mksh /$objtype/bin/ape/sh
UNINSTALLCOMMAND=/bin/rc -c 'cd /sys/src/ape/cmd/pdksh && mk install'

</sys/ports/Mk/mkfile
