</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='Optionally use mksh as default /bin/sh in APE'
DEPS=shells/mksh

BUILDPATH=work/
PATCHES=patches
BUILDCOMMAND=
INSTALLCOMMAND=/bin/rc -c 'cp sh.rc /rc/bin/ape/sh && chmod +x /rc/bin/ape/sh'
CLEANCOMMAND=rm sh.rc
UNINSTALLCMD=rm /rc/bin/ape/sh

</sys/ports/Mk/mkfile