</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='libpoll for APE'
VERSION=1

WEBSOURCE=https://9p.io/sources/contrib/fgb/tar/poll.tgz
BUILDPATH=work/poll
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
