</$objtype/mkfile

archmask=amd64

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='Inferno® is a distributed operating system'

HGSOURCE=https://bitbucket.org/inferno-os/inferno-os /usr/inferno
BUILDPATH=/usr/inferno
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=rm -rf /usr/inferno

</sys/ports/Mk/mkfile
