</$objtype/mkfile

archmask=amd64

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='Inferno® is a distributed operating system'

HGSOURCE=https://bitbucket.org/inferno-os/inferno-os /usr/inferno
BUILDPATH=/usr/inferno
BUILDCOMMAND=rc -c 'mk mkdirs && path=($path /usr/inferno/Plan9/$objtype/bin) mk install'
INSTALLCOMMAND=fortune
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=rc -c 'chmod u+w /usr/inferno/^(* */* */*/*) && rm -rf /usr/inferno'

</sys/ports/Mk/mkfile
