</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='gnulib complement for APE'
VERSION=1
DEPS=ape-libs/headers ape-libs/libpoll

WEBSOURCE=http://erislabs.net/ianb/projects/gnulib/gnulib-20140202-stable.tar.gz
BUILDPATH=work/gnulib-20140202-stable/lib/
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
