</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='XML library for APE'
VERSION=2.9.2

WEBSOURCE=http://xmlsoft.org/sources/libxml2-2.9.2.tar.gz
BUILDPATH=work/libxml2-2.9.2
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
