</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='The Go fonts'
VERSION=0

9PSERVER=9front
9PFILE=/n/extra/font.Go-Bold-Italic.tgz /n/extra/font.Go-Bold.tgz /n/extra/font.Go-Italic.tgz /n/extra/font.Go-Medium-Italic.tgz /n/extra/font.Go-Medium.tgz /n/extra/font.Go-Mono-Bold-Italic.tgz /n/extra/font.Go-Mono-Bold.tgz /n/extra/font.Go-Mono-Italic.tgz /n/extra/font.Go-Mono.tgz /n/extra/font.Go-Regular.tgz
BUILDPATH=work
BUILDCOMMAND=echo No build.
INSTALLCOMMAND=dircp ./ /lib/font/bit
CLEANCOMMAND=rm -r Go-*
UNINSTALLCOMMAND=rm -r /lib/font/bit/Go-*

</sys/ports/Mk/mkfile
