</$objtype/mkfile
TARG=ocamlyacc
OFILES=\
	closure.$O\
	error.$O\
	lalr.$O\
	lr0.$O\
	main.$O\
	mkpar.$O\
	output.$O\
	reader.$O\
	skeleton.$O\
	symtab.$O\
	verbose.$O\
	warshall.$O
HFILES=defs.h version.h
CLEANFILES=version.h
BIN=../boot

</sys/src/cmd/mkone

CC=pcc
CFLAGS=\
	-I../byterun\
	-D_BSD_EXTENSION\
	-D_C99_SNPRINTF_EXTENSION\
	-D_POSIX_SOURCE\
	-DCAML_NAME_SPACE\
	-Bc

version.h : ../VERSION
	echo '#define OCAML_VERSION "'^`{sed -e 1q ../VERSION | tr -d ''}^'"' > version.h
