</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='Gopher server by Sean Caron (scaron@umich.edu)'
VERSION='1.0'

WEBSOURCE=http://9.postnix.us/code/ports/gophers.tgz
WORKFILE=gophers.tgz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/gophers
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
