</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='Gopher server by Sean Caron (scaron@umich.edu)'
VERSION=0

WEBSOURCE=http://9.postnix.pw/code/ports/gophers.tgz
BUILDPATH=work/gophers
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
