</$objtype/mkfile

# imported from https://code.9front.org/hg/ocaml

OWNER='Ben Purcell <spew@cbza.org>'
DESCRIPTION='Ocaml'
MAJORVERSION=4.07
MINORVERSION=1
BASEVERSION=$MAJORVERSION.$MINORVERSION
VERSION=$BASEVERSION-1

WEBSOURCE=http://caml.inria.fr/pub/distrib/ocaml-$MAJORVERSION/ocaml-$BASEVERSION.tar.gz
PATCHES=files
BUILDPATH=work/ocaml-$BASEVERSION
BUILDCOMMAND=mk
INSTALLCOMMAND=/bin/rc -c '''mkdir -p /sys/lib/ocaml && mk install'''
NOCLEAN=1
UNINSTALLCOMMAND=/bin/rc -c '''rm -rf /bin/^(ocaml ocamlc ocamldep ocamllex ocamlmklib ocamlrun ocamlyacc /sys/lib/ocaml)'''

</sys/ports/Mk/mkfile
