</$objtype/mkfile

OWNER='kvik <vp@kvik.link>'
DESCRIPTION='copy files and directories, fast'
VERSION=0.1

WEBSOURCE=https://bitbucket.org/k-vik/clone/downloads/clone.v0.1.tgz
BUILDPATH=work
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
