</$objtype/mkfile

OWNER='kvik <vp@kvik.link>'
DESCRIPTION='copy files and directories, fast'
VERSION=0.2

WEBSOURCE=http://code.a-b.xyz/clone/snapshot/clone-0.2.1.tar
BUILDPATH=work/clone-0.2.1
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
