</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='tex(1) from Plan 9 2e'
VERSION=1

WEBSOURCE=http://9.postnix.us/code/ports/tex.tgz
WORKFILE=tex.tgz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/tex
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
