</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='tex(1) from Plan 9 2e'
VERSION=1

WEBSOURCE=http://9.postnix.us/code/ports/tex.tgz
BUILDPATH=work/tex
BUILDCOMMAND=prep; mk all
INSTALLCOMMAND=mk install; cp man/tex /sys/man/1/tex; echo Commands installed to /sys/lib/texmf/bin
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=mk uninstall; tear

</sys/ports/Mk/mkfile
