</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='png library for APE'
VERSION=1.6.17
DEPS=ape-libs/zlib

WEBSOURCE=https://download.sourceforge.net/libpng/libpng-$VERSION.tar.gz
BUILDPATH=work/libpng-$VERSION
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
