</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='png library for APE'
VERSION=1.6.17
DEPS=ape-libs/zlib

WEBSOURCE=http://garr.dl.sourceforge.net/project/libpng/libpng16/1.6.17/libpng-1.6.17.tar.gz
WORKFILE=libpng-1.6.17.tar.gz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/libpng-1.6.17/
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
