</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='JPEG library for APE'
VERSION=9a

WEBSOURCE=http://ijg.org/files/jpegsrc.v9a.tar.gz
BUILDPATH=work/jpeg-9a
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
