</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='C-language version of lzip'
VERSION=1.7-rc1
DEPS=ape-libs/headers

WEBSOURCE=http://download.savannah.gnu.org/releases/lzip/clzip/clzip-1.7-rc1.tar.gz
WORKFILE=clzip-1.7-rc1.tar.gz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/clzip-1.7-rc1
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
