</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='DISCOUNT is an implementation of John Gruber Markdown by David Parsons <orc@pell.portland.or.us>'
VERSION=2.2.5

WEBSOURCE=https://github.com/Orc/discount/archive/$VERSION.tar.gz
WORKFILE=discount-$VERSION.tar.gz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/discount-$VERSION/Plan9
BUILDCOMMAND=mk build
TESTCOMMAND=mk test
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
