</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='git linkable library'
VERSION=9999

HGSOURCE=https://bitbucket.org/oridb/libgit2
HGREV=24f2f7b3633c
BUILDPATH=work/libgit2
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
