</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='Google Go language'
DEPS=app-misc/ca-certificates

WEBSOURCE=https://storage.googleapis.com/golang/go1.4.2.src.tar.gz
WORKFILE=go1.4.2.src.tar.gz
EXTRACTCOMMAND=/bin/tar xzvf
BUILDPATH=work/go/src
BUILDCOMMAND=./make.rc
INSTALLCOMMAND=fortune /lib/rob
CLEANCOMMAND=./clean.rc
UNINSTALLCOMMAND=fortune /lib/rsc
MESSAGE='To make use of go you must bind '`{pwd}'/work/go/bin over /bin and set $GOPATH.'

</sys/ports/Mk/mkfile
