</$objtype/mkfile

# TODO: arm support

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='Google Go language'
VERSION=1.13.4
BOOTSTRAP=1.13.1
DEPS=app-misc/ca-certificates dev-lang/gobootstrap

# local variables
# keep bootstrap in sync with dev-lang/gobootstrap
GOROOT_BOOTSTRAP=/sys/lib/go/$objtype-$BOOTSTRAP-bootstrap
GOROOT_FINAL=/sys/lib/go/$objtype-$VERSION

WEBSOURCE=https://dl.google.com/go/go$VERSION.src.tar.gz
BUILDPATH=work/go
BUILDCOMMAND='cd src; ./make.rc'
CLEANCOMMAND='GOROOT=..; cd src; ./clean.rc'
INSTALLCOMMAND=mkdir -p $GOROOT_FINAL && \
	dircp . /sys/lib/go/$objtype-$VERSION && \
	cp bin/^(go gofmt) /$objtype/bin

UNINSTALLCOMMAND=rm -rf $GOROOT_FINAL \
	/$objtype/bin/^(go gofmt)

</sys/ports/Mk/mkfile
