</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='grio has the background image patch and colour options'
VERSION=0

HGSOURCE=https://bitbucket.org/mycroftiv/grio
BUILDPATH=work/grio
BUILDCOMMAND=mk
CLEANCOMMAND=mk nuke
INSTALLCOMMAND=mk install
UNINSTALLCOMMAND=rm /$objtype/bin/grio

</sys/ports/Mk/mkfile
