</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='automatic generation of mkfiles'
VERSION=1

9PSERVER=9pio
9PFILE=/n/9pio/contrib/steve/mkmk.tbz
BUILDPATH=work/mkmk
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
