</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='automatic generation of mkfiles'
VERSION=1

WEBSOURCE=http://plan9.bell-labs.com/sources/contrib/steve/mkmk.tbz
WORKFILE=mkmk.tbz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/mkmk
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
