</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='fmemopen() for APE'
VERSION=1

WEBSOURCE=http://plan9.bell-labs.com/sources/contrib/staal1978/ports/src/simple_fmemopen.tbz
WORKFILE=simple_fmemopen.tbz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/fmemopen
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
