</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='fgb''s snake/nibbles clone'
VERSION=1

WEBSOURCE=http://9.postnix.us/code/ports/snake.tgz
BUILDPATH=work/snake
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=rm /$objtype/bin/games/snake

</sys/ports/Mk/mkfile
