</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='portscan is a tcp port scanner for Plan 9 by Sean Caron (scaron@umich.edu)'
VERSION='1.0'

WEBSOURCE=http://9.postnix.us/code/ports/portscan.tgz
WORKFILE=portscan.tgz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/portscan
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
