</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='TRE regex library for APE'
VERSION=0.8.0
DEPS=ape-libs/libutf8 ape-libs/libgetopt

WEBSOURCE=http://laurikari.net/tre/tre-0.8.0.tar.bz2
BUILDPATH=work/tre-0.8.0/
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
