</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='Motion JPEG AVI audio and video player'

HGSOURCE=https://bitbucket.org/mischief/avi
BUILDPATH=work/avi
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
