</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='immediate mode graphics library'
VERSION=0

HGSOURCE=https://bitbucket.org/mischief/libnuklear
BUILDPATH=work/libnuklear
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
