<../config/mkfile
TARG=ocamlrun
BIN=../boot
OFILES=main.$O
LIB=libcamlrun.a ../otherlibs/unix/libunix.a ../otherlibs/str/libstr.a ../otherlibs/threads/libthreads.a
</sys/src/cmd/mkone

libcamlrun.a:
	mk -f mklib

sysinstall: $O.out
	cp $O.out /$objtype/bin/$TARG
