</$objtype/mkfile

PORTNAME=sys-apps/rngd
OWNER='Matthew Veety <mveety@mveety.com>'
DESCRIPTION='Random number generator filesystem'

HGSOURCE='https://bitbucket.org/mischief/rngd'
BUILDPATH=work/
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALL=/$objtype/bin/rngd

</sys/ports/Mk/mkfile
