</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='zlib compression library for APE'
VERSION=1.2.7

WEBSOURCE=https://ftp.osuosl.org/pub/libpng/src/archive/gz/zlib/zlib-$VERSION.tar.gz
WORKFILE=zlib-$VERSION.tar.gz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/zlib-$VERSION
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
