</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='bunzip2 compression library for APE'
VERSION=1.0.6

WEBSOURCE=https://spacehopper.org/mirrors/bzip2-$VERSION.tar.gz
BUILDPATH=work/bzip2-$VERSION
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
