</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='un-ACE utility'
VERSION=1.2b
#DEPS=

WEBSOURCE=http://ibiblio.org/pub/linux/utils/compress/unace-1.2b.tar.gz
BUILDPATH=work/unace-1.2b
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
