</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='steve''s pptfs'
VERSION=1

WEBSOURCE=http://9.postnix.pw/code/ports/pptfs.tgz
BUILDPATH=work/pptfs
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=rm /$objtype/bin/pptfs

</sys/ports/Mk/mkfile
