</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='mother mail client'
VERSION=0

WEBSOURCE=http://plan9.stanleylieber.com/rc/mother
BUILDPATH=work
INSTALLCOMMAND=/bin/rc -c 'cp mother /rc/bin/mother && chmod +x /rc/bin/mother'
UNINSTALL=/rc/bin/mother

</sys/ports/Mk/mkfile
