</$objtype/mkfile

PORTNAME='mail-client/mother'
OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='mother'

WEBSOURCE=http://plan9.stanleylieber.com/rc/mother
WORKFILE=mother
BUILDPATH=work
INSTALLCOMMAND=/bin/rc -c 'cp mother /rc/bin/mother && chmod +x /rc/bin/mother'

</sys/ports/Mk/mkfile
