OCAMLRUN=../../boot/ocamlrun
OCAMLC=$OCAMLRUN ../../boot/ocamlc -nostdlib -I ../../stdlib
OCAMLFLAGS=-use-prims ../../byterun/primitives -strict-sequence -absname -w +a-4-9-41-42-44-45-48 -g -warn-error A -bin-annot -nostdlib -safe-string -strict-formats -c

$LIBNAME.cma: $CMOFILES
	$OCAMLC -a -o $LIBNAME.cma $CMOFILES

%.cmi: %.mli
	$OCAMLC $OCAMLFLAGS $stem.mli

%.cmo: %.ml
	$OCAMLC $OCAMLFLAGS $stem.ml
<.depend
