
info:VQ:
	echo 'Name: '^$PORTNAME
	echo 'Description: '^$DESCRIPTION
	echo 'Complain to: '^$OWNER

fetch:VQ:
	fn runvar {
		$*
	}
	if(! test -e work/)
		mkdir work/
	if(test -e /env/WEBSOURCE){
		webfs
		. /sys/ports/Config/ports.conf
		hget $WEBSOURCE > work/$WORKFILE
		$EXTRACTCOMMAND=($EXTRACTCOMMAND 'work/'^$WORKFILE)
		runvar $EXTRACTCOMMAND
	}
	if(test -e /env/CONTRIBSOURCE){
		9fs sources
		dircp $CONTRIBSOURCE work/
	}

build:VQ:
	fn runvar {
		$*
	}
	if(test -e /env/PATCHES){
		dircp $PATCHES $BUILDPATH
	}
	. /sys/ports/Config/ports.conf
	cd $BUILDPATH
	for(i in $BUILDFOR){
		objtype=$i
		runvar $BUILDCOMMAND
	}

install:VQ:
	fn runvar {
		$*
	}
	. /sys/ports/Config/ports.conf
	cd $BUILDPATH
	for(i in $BUILDFOR){
		objtype=$i
		runvar $INSTALLCOMMAND
	}

clean:VQ:
	fn runvar {
		$*
	}
	. /sys/ports/Config/ports.conf
	cd $BUILDPATH
	runvar $CLEANCOMMAND

nuke:VQ:
	. /sys/ports/Config/ports.conf
	rm -rf work/
