</$objtype/mkfile
DIRS=doc testsuite 
TARG=lzip
OFILES=carg_parser.$O decoder.$O encoder.$O encoder_base.$O fast_encoder.$O file_index.$O list.$O main.$O 
BIN=/$objtype/bin
HFILES=encoder_base.h lzip.h 

</sys/src/cmd/mkone

CC=pcc
LD=pcc
CFLAGS=-c -I. -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_C99_SNPRINTF_EXTENSION -DPROGVERSION="$VERSION" -DPLAN9

main.$O: fast_encoder.h encoder.h decoder.h carg_parser.h /sys/include/ape/limits.h 
fast_encoder.$O: fast_encoder.h 
encoder_base.$O: 
encoder.$O: encoder.h 
decoder.$O: decoder.h 
carg_parser.$O: carg_parser.h 

install:V:
	cp doc/clzip.1 /sys/man/1/lzip

uninstall:V:
	rm -f /sys/man/1/lzip $BIN/$TARG
