</$objtype/mkfile

OWNER='Matthew Veety <mveety@gmail.com>'
DESCRIPTION='Modified rio'
VERSION='1'

9PSERVER=sources
9PDIR=/n/sources/contrib/anothy/src/cmd/nile
BUILDPATH=work
PATCHES=files/
BUILDCOMMAND=mk
INSTALLCOMMAND=mk portinstall
CLEANCOMMAND=mk clean
UNINSTALL=/$objtype/bin/nile

</sys/ports/Mk/mkfile
