</$objtype/mkfile

PORTNAME='rio/nile'
OWNER='Matthew Veety <mveety@gmail.com>'
DESCRIPTION='Modified rio'

CONTRIBSOURCE='/n/sources/contrib/anothy/src/cmd/nile'
BUILDPATH='work/'
PATCHES='files/'
BUILDCOMMAND='mk'
INSTALLCOMMAND=('mk' 'portinstall')
CLEANCOMMAND=('mk' 'clean')

</sys/ports/Mk/mkfile
