</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='mercurial'
VERSION=3.4.1

WEBSOURCE=http://mercurial.selenic.com/release/mercurial-3.4.1.tar.gz
WORKFILE=mercurial-3.4.1.tar.gz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/mercurial-3.4.1
BUILDCOMMAND=python setup.py --pure build
INSTALLCOMMAND=python setup.py --pure install
CLEANCOMMAND=python setup.py --pure clean --all
UNINSTALLCOMMAND=/bin/rc -c 'rm -r /sys/lib/python/bin/hg /sys/lib/python/lib/python2.5/site-packages/^(hgext mercurial mercurial-3.4.1-py2.5.egg-info'
MESSAGE='bind -b /sys/lib/python/bin /bin'

</sys/ports/Mk/mkfile
