</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='random number generator test'
VERSION=0

9PSERVER=9pio
9PFILE=/n/9pio/contrib/bakul/rngtest.tar.gz
BUILDPATH=work/rngtest/src
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALL=/$objtype/bin/ape/rngtest

</sys/ports/Mk/mkfile
