</$objtype/mkfile

OWNER='Matthew Veety <mveety@mveety.com>'
DESCRIPTION='HTML5 compliant web browser for plan9'

9PSERVER=9pio
9PDIR=/n/9pio/contrib/fgb/root/sys/src/cmd/scheme
BUILDPATH=work/
BUILDCOMMAND=mk all
INSTALLCOMMAND=rc ../install
CLEANCOMMAND=mk clean
UNINSTALL=/$objtype/bin/scheme

</sys/ports/Mk/mkfile
