</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='TinyScheme is a lightweight Scheme interpreter'
VERSION=1.41

WEBSOURCE=https://download.sourceforge.net/tinyscheme/tinyscheme-$VERSION.tar.gz
BUILDPATH=work/tinyscheme-$VERSION
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
