</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='CA certificate bundle'
VERSION=0

WEBSOURCE=https://curl.haxx.se/ca/cacert.pem
BUILDPATH=work/
BUILDCOMMAND=fortune /lib/uriel
CLEANCOMMAND=fortune /lib/uriel
INSTALLCOMMAND=/bin/rc -c '''cp cacert.pem /sys/lib/tls/ca.pem'''
UNINSTALL=/sys/lib/tls/ca.pem

</sys/ports/Mk/mkfile
