</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='webfs client library'
VERSION=0

HGSOURCE=https://bitbucket.org/mischief/libwebfs
BUILDPATH=work/libwebfs
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
