</$objtype/mkfile

OWNER='Matthew Veety <mveety@mveety.com>'
DESCRIPTION='HTML5 compliant web browser for plan9'

9PSERVER=9front.org
9PDIR=/n/9front.org/9front/sys/src/cmd/mothra
BUILDPATH=work/
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALL=/$objtype/bin/mothra

</sys/ports/Mk/mkfile
