</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='quake 2 port by qwx'
VERSION=1

WEBSOURCE=http://9.postnix.us/code/ports/qk2.tgz
WORKFILE=qk2.tgz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/qk2
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=rm /$objtype/bin/quake2

</sys/ports/Mk/mkfile
