</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='A Pure Go Git Implementation'
VERSION=20191115
DEPS=dev-lang/go
COMMIT=bd1b53f27a5fbda45f054a748d0ced1022c34a0e

WEBSOURCE=https://github.com/driusan/dgit/archive/$COMMIT.tar.gz
BUILDPATH=work/dgit-$COMMIT
BUILDCOMMAND=go build -mod vendor
CLEANCOMMAND=go clean
# to git or not to git?
INSTALLCOMMAND=cp dgit /$objtype/bin/dgit
UNINSTALLCOMMAND=rm -f /$objtype/bin/dgit

</sys/ports/Mk/mkfile
