</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='A Pure Go Git Implementation'
VERSION=20181013
DEPS=dev-lang/go

COMMIT=49625dcca1eed1cae4ccd3eb750df6024f074bc8

WEBSOURCE=https://github.com/driusan/dgit/archive/$COMMIT.tar.gz
BUILDPATH=work/dgit-$COMMIT
BUILDCOMMAND=go build -mod vendor
CLEANCOMMAND=go clean
# to git or not to git?
INSTALLCOMMAND=cp dgit /$objtype/bin/dgit
UNINSTALLCOMMAND=rm -f /$objtype/bin/dgit

</sys/ports/Mk/mkfile
