</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='curl'
VERSION='7.28.1'
DEPS=textproc/gawk ape-libs/zlib

WEBSOURCE=http://9p.io/sources/contrib/staal1978/pkg/curl-7.28.1.tbz
WORKFILE=curl-7.28.1.tbz
EXTRACTCOMMAND=tar xvf
BUILDPATH=work/sys/src/pkg/curl
BUILDCOMMAND=ape/psh -c make
INSTALLCOMMAND=cp src/curl /$objtype/bin/curl
CLEANCOMMAND=ape/psh -c make clean
UNINSTALLCOMMAND=rm /$objtype/bin/curl

</sys/ports/Mk/mkfile
