</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='Royalty-free, highly versatile audio codec'
VERSION=0.1.10
DEPS=media-libs/opus

WEBSOURCE=https://archive.mozilla.org/pub/opus/opus-tools-$VERSION.tar.gz
BUILDPATH=work/opus-tools-$VERSION
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
