</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='concurrent tcp port scanner'
VERSION=0

9PSERVER=9front
9PFILE=/n/extra/netscan.c
BUILDPATH=work/
BUILDCOMMAND=/bin/rc -c '''s=netscan; $CC $s.c && $LD -o $O.$s $s.$O'''
CLEANCOMMNAD=/bin/rc -c '''s=netscan; rm -f $O.$s $s.$O'''
INSTALLCOMMAND=/bin/rc -c '''s=netscan; cp $O.$s /$objtype/bin/$s'''
UNINSTALL=/$objtype/bin/netscan

</sys/ports/Mk/mkfile
