</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='concurrent tcp port scanner'

9PSERVER=9front
9PFILE=/n/extra/netscan.c
WORKFILE=netscan.c
BUILDPATH=work/
BUILDCOMMAND=/bin/rc -c '''s=netscan; $CC $s.c && $LD -o $O.$s $s.$O'''
NOCLEAN=1
INSTALLCOMMAND=/bin/rc -c '''s=netscan; cp $O.$s /$objtype/bin/$s'''
UNINSTALL=/$objtype/bin/netscan

</sys/ports/Mk/mkfile
