</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='stefanha''s vim'
VERSION=1

WEBSOURCE=http://9.postnix.us/code/ports/vim.tgz
BUILDPATH=work/vim
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=rm /$objtype/bin/vim; rm /$objtype/bin/xxd

</sys/ports/Mk/mkfile
