</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='stefanha''s vim'
VERSION=1

WEBSOURCE=http://9.postnix.pw/code/ports/vim.tgz
BUILDPATH=work/vim
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=rm -f /$objtype/bin/vim /$objtype/bin/xxd

</sys/ports/Mk/mkfile
