</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='Pegasus is another httpd that runs on Plan9 4ed.'
VERSION=2.8e

WEBSOURCE=http://p9.nyx.link/netlib/pegasus/pegasus-$VERSION.tgz
BUILDPATH=work/pegasus-$VERSION/httpd
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALL=/$objtype/bin/httpd

</sys/ports/Mk/mkfile
