</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='Provides GNU screen-like functionality via a 9p fs of io Hubs.'

HGSOURCE=https://bitbucket.org/mycroftiv/hubfs
BUILDPATH=work/hubfs
BUILDCOMMAND=mk all
CLEANCOMMAND=mk nuke
INSTALLCOMMAND=mk install
UNINSTALLCOMMAND=

</sys/ports/Mk/mkfile
