</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='Suckless.org base utilities for APE'
VERSION=1
DEPS=ape-libs/newlib-libgen ape-libs/gnulib ape-libs/fmemopen

WEBSOURCE=http://git.suckless.org/sbase/snapshot/sbase-master.tar.bz2
BUILDPATH=work/sbase-master
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk installall
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=/bin/rc -c 'mk nuke && cd /sys/src/ape/cmd && mk install'

</sys/ports/Mk/mkfile
