</$objtype/mkfile

OWNER='Matthew Veety <mveety@mveety.com>'
DESCRIPTION='Emulator for vintage hardware'

9PSERVER=9front.org
9PFILE=/n/9front.org/extra/simh.tgz
WORKFILE=simh.tgz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/simh
BUILDCOMMAND=plan9/build
INSTALLCOMMAND=cp BIN/* /$objtype/bin/
CLEANCOMMAND=rm *.$O
UNINSTALLCOMMAND=rm '/'^$objtype^'/bin/'^('pdp8' 'pdp10' 'pdp11' 'vax' 'vax780')

</sys/ports/Mk/mkfile
