</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='libintl replacement/stubs and gettext utility'
VERSION=1

WEBSOURCE=https://github.com/sabotage-linux/gettext-tiny/archive/master.zip
WORKFILE=master.zip
EXTRACTCOMMAND=unzip -f
BUILDPATH=work/gettext-tiny-master/
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
