</$objtype/mkfile

PORTNAME='media-sound/volctl'
OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='graphical volume controller'

BUILDPATH=work/
INSTALLCOMMAND=/bin/rc -c 's=volctl; hget http://9.offblast.org/stuff/$s.c > $s.c \
	&& $CC $s.c \
	&& $LD -o $O.$s $s.$O \
	&& cp $O.$s /$objtype/bin/$s'

</sys/ports/Mk/mkfile
