</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='Recursive grep(1) by stallion'
VERSION=1

WEBSOURCE=http://9.postnix.pw/code/ports/gr
EXTRACTCOMMAND=
BUILDPATH=work
BUILDCOMMAND=cp gr /rc/bin/gr
INSTALLCOMMAND=echo Build already installs, sorry. ☺
CLEANCOMMAND=echo Nothing to clean, sorry. ☺
UNINSTALLCOMMAND=rm /rc/bin/gr


</sys/ports/Mk/mkfile
