</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='go ssh client'
DEPS=dev-lang/go

BUILDPATH=work

# hack to work around path name length issue.
BUILDCOMMAND=/bin/rc -ec 'rfork ne; \
	mkdir gopath; \
	bind -c gopath /n/gopath; \
	GOPATH=/n/gopath; \
	$PORTS/dev-lang/go/work/go/bin/go get bitbucket.org/mischief/scpu;'
CLEANCOMMAND=rm -r gopath/bin
INSTALLCOMMAND=cp gopath/bin/scpu /$objtype/bin/scpu
UNINSTALLCOMMAND=rm /$objtype/bin/scpu

</sys/ports/Mk/mkfile
