</$objtype/mkfile

OWNER='Aaron Bieber <aaron@bolddaemon.com>'
DESCRIPTION='Git for Plan9'
VERSION=20191115

COMMIT=4d43ed79a82c470f0b6a2b1a1b159e6749523b4f

WEBSOURCE=https://github.com/oridb/git9/archive/$COMMIT.tar.gz

BUILDPATH=work/git9-$COMMIT
BUILDCOMMAND=mkdir -p /sys/lib/git
CLEANCOMMAND=mk clean
INSTALLCOMMAND=mk install
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
