</$objtype/mkfile

OWNER='Aaron Bieber <aaron@bolddaemon.com>'
DESCRIPTION='Git for Plan9'
VERSION=20191115

COMMIT=65b772ed948f2841733f44eefc1f1f7df413c68a

WEBSOURCE=https://github.com/oridb/git9/archive/$COMMIT.tar.gz

BUILDPATH=work/git9-$COMMIT
BUILDCOMMAND=mkdir -p /sys/lib/git
CLEANCOMMAND=mk clean
INSTALLCOMMAND=mk install
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
