</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='GNU Pth userspace pthread library for APE'
VERSION=1

WEBSOURCE=http://plan9.bell-labs.com/sources/contrib/staal1978/pkg/pth-2.0.7.tbz
WORKFILE=pth-2.0.7.tbz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/sys/src/pkg/pth
PATCHES=files
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
