</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='GNU Pth userspace pthread library for APE'
VERSION=1

WEBSOURCE=https://gnu.cu.be/pth/pth-2.0.7.tar.gz
BUILDPATH=work/pth-2.0.7/
PATCHES=files
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
