</$objtype/mkfile

archmask=amd64

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='LZO compression library'
VERSION=2.0.9
DEPS=ape-libs/headers

WEBSOURCE=http://www.oberhumer.com/opensource/lzo/download/lzo-2.09.tar.gz
BUILDPATH=work/lzo-2.09/src
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
