</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='Suckless.org base utilities for APE'
VERSION=1
#DEPS ape-libs/tre ape-libs/newlib-libgen

WEBSOURCE=http://git.suckless.org/sbase/snapshot/sbase-master.tar.bz2
WORKFILE=sbase-master.tar.bz2
EXTRACTCOMMAND=/bin/tar xzvf
BUILDPATH=work/sbase-master
PATCHES=files
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk installall
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=/bin/rc -c 'mk nuke && cd /sys/src/ape/cmd && mk install'

</sys/ports/Mk/mkfile
