</$objtype/mkfile

OWNER='Nick Owens <mischief@offblast.org>'
DESCRIPTION='decontrib'

9PSERVER=sources
9PFILE=/n/sources/contrib/john/decontrib
WORKFILE=decontrib
INSTALLCOMMAND=chmod +x decontrib && cp decontrib /rc/bin/decontrib
UNINSTALL=/rc/bin/decontrib

</sys/ports/Mk/mkfile
