</$objtype/mkfile

OWNER='Matthew Veety <mveety@gmail.com>'
DESCRIPTION='File based irc client'
VERSION='1'

9PSERVER=9front.org
9PFILE=/n/9front.org/extra/irc7.tgz
BUILDPATH=work/irc7
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=rm /$objtype/bin/irc /$objtype/bin/ircsrv /sys/man/1/irc

</sys/ports/Mk/mkfile
