</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='libutf8 wchar library for APE'
VERSION=0.8.1

WEBSOURCE=http://www.haible.de/bruno/libutf8-$VERSION.tar.gz
BUILDPATH=work/libutf8-$VERSION
BUILDCOMMAND=mk all
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
