</$objtype/mkfile

OWNER='Matthew Veety <mveety@mveety.com>'
DESCRIPTION='Scheme 9 from Empty Space'
VERSION=20180823

WEBSOURCE=http://t3x.org/s9fes/s9fes-$VERSION.tgz
BUILDPATH=work/s9
BUILDCOMMAND=mk
INSTALLCOMMAND=mk inst
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk deinst

</sys/ports/Mk/mkfile
