</$objtype/mkfile

DESCRIPTION='Files needed to use map(7)'
OWNER='Matthew Veety <mveety@gmail.com>'
VERSION=0

WEBSOURCE=http://www.cs.dartmouth.edu/~doug/wdbii.tar.gz
BUILDCOMMAND=fortune
BUILDPATH=./
INSTALLCOMMAND=dircp work/ /lib/map
CLEANCOMMAND=fortune
UNINSTALLCOMMAND=rc -c 'cd /lib/map ; cp README /tmp ; rm * ; cp /tmp/README ./ ; rm /tmp/README'

</sys/ports/Mk/mkfile
