</$objtype/mkfile

OWNER='Jens Staal <staal1978@gmail.com>'
DESCRIPTION='YASM pure C re2c implementation'
VERSION=1
#DEPS=

WEBSOURCE=https://github.com/yasm/yasm/archive/master.zip
BUILDPATH=work/yasm-master/tools/re2c
PATCHES=files
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALLCOMMAND=mk nuke

</sys/ports/Mk/mkfile
