</$objtype/mkfile
TARG=agrep
OFILES=agrep.$O 
BIN=/$objtype/bin
LIB=/$objtype/lib/ape/libtre.a

</sys/src/cmd/mkone

CC=pcc
LD=pcc
CFLAGS=-c -B -I.. -I../lib -DHAVE_CONFIG_H -D_POSIX_SOURCE -D_BSD_EXTENSION

agrep.$O: 

nuke:V:
	rm -f $BIN/agrep
