</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='A nominally HTTP/1.1 compliant web server for Plan 9 by Sean Caron (scaron@umich.edu)'
VERSION=1.0

WEBSOURCE=http://9.postnix.pw/code/ports/bijou.tgz
BUILDPATH=work/bijou-1.0/src
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=mk uninstall

</sys/ports/Mk/mkfile
