</$objtype/mkfile

OWNER='Sean Hinchee <henesy.dev@gmail.com>'
DESCRIPTION='quake 1 port by qwx'
VERSION=1

WEBSOURCE=http://9.postnix.us/code/ports/qk1.tgz
WORKFILE=qk1.tgz
EXTRACTCOMMAND=tar xzvf
BUILDPATH=work/qk1
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk nuke
UNINSTALLCOMMAND=rm /$objtype/bin/quake

</sys/ports/Mk/mkfile
