</$objtype/mkfile

OWNER='Matthew Veety <mveety@gmail.com>'
DESCRIPTION='Modified rio'
VERSION=0

9PSERVER=9pio
9PDIR=/n/9pio/contrib/anothy/src/cmd/nile
BUILDPATH=work
BUILDCOMMAND=mk
INSTALLCOMMAND=mk install
CLEANCOMMAND=mk clean
UNINSTALL=/$objtype/bin/nile /sys/man/1/nile

</sys/ports/Mk/mkfile
